<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <title>用户登录</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Joychao <joy@joychao.cc>">    
  </head>
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  <link class="bootstrap library" rel="stylesheet" type="text/css" href="http://sandbox.runjs.cn/js/sandbox/bootstrap-2.2.0/css/bootstrap.min.css">
  <script class="bootstrap library" src="http://sandbox.runjs.cn/js/sandbox/jquery/jquery-1.7.2.min.js" type="text/javascript"></script>
  <script class="bootstrap library" src="http://sandbox.runjs.cn/js/sandbox/bootstrap-2.2.0/js/bootstrap.min.js" type="text/javascript"></script>
  </head>
  <body>
      <?php $form = ActiveForm::begin([
          'id' => 'login-form',
          'options' => ['class' => 'form-horizontal'],
  /*        'fieldConfig' => [
              'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
              'labelOptions' => ['class' => 'col-lg-1 control-label'],
          ],*/
      ]); ?>
      <div class="container">
          <section class="loginBox row-fluid">
            <section class="span7 left">
              <h2>订单管理系统</h2>
              <p><input type="text" name="username" placeholder="Username"/></p>
              <p><input type="password" name="password" placeholder="Password"/></p>
              <section class="row-fluid">
                <label class="checkbox">
                  <input type="checkbox" name='rememberMe'> 自动登录
                </label>
              <section class="span1">
                 <input type="submit" value=" 登录 " class="btn btn-primary"> 
              </section>
              </section>
            </section>
            <section class="span5 right">
              <h2>订单管理系统</h2>
              <section>
                <p>这里有一段文字啊，很多的文字啊，太多太多的文字了，主要可以介绍介绍注册的好处和公司或者项目概况。。。</p>
              </section>
            </section>
          </section><!-- /loginBox -->
      </div> <!-- /container -->
    <?php ActiveForm::end(); ?>
  </body>
</html>

      <style>*{margin:0;padding: 0;}
      .loginBox{width:420px;height:250px;padding:0 20px;border:1px solid #fff; color:#000; margin-top:40px; border-radius:8px;background: white;box-shadow:0 0 15px #222; background: -moz-linear-gradient(top, #fff, #efefef 8%);background: -webkit-gradient(linear, 0 0, 0 100%, from(#f6f6f6), to(#f4f4f4));font:11px/1.5em 'Microsoft YaHei' ;position: absolute;left:50%;top:50%;margin-left:-210px;margin-top:-115px;}
      .loginBox h2{height:45px;font-size:20px;font-weight:normal;}
      .loginBox .left{border-right:1px solid #ccc;height:100%;padding-right: 20px; }</style>
          <script></script>
  
<!-- Generated by RunJS (Tue May 13 11:49:48 CST 2014) 2ms -->